title = "openMSX"
baseurl = "http://openmsx.damad.be/"
languageCode = "en-us"
theme = "beautifulhugo"

[Params]
  subtitle = "the MSX emulator that aims for perfection"
  logo = "img/penguin.png"
  favicon = "img/favicon.ico"
  Paginate = 3

[Author]
  name = "The openMSX Team"
  facebook = "openMSX"
  github = "openMSX"
  
[[menu.main]]
    identifier = "doc"
    name = "Doc"
    weight = 1

[[menu.main]]
    parent = "doc"
    name = "Documentation"
    url = "/page/documentation/"
    weight = 1
    
[[menu.main]]
    parent = "doc"
    name = "Screenshots"
    url = "/page/screenshots/"
    weight = 2
    
[[menu.main]]
    parent = "doc"
    name = "Features"
    url = "/page/features/"
    weight = 3
    
[[menu.main]]
    identifier = "download"
    name = "Download"
    weight = 2

[[menu.main]]
    parent = "download"
    name = "64bit Windows"
    url = "https://github.com/openMSX/openMSX/releases/download/RELEASE_0_13_0/openmsx-0.13.0-windows-vc-x64-bin-msi.zip"
    weight = 1
    
[[menu.main]]
    parent = "download"
    name = "32bit Windows"
    url = "https://github.com/openMSX/openMSX/releases/download/RELEASE_0_13_0/openmsx-0.13.0-windows-vc-x86-bin-msi.zip"
    weight = 2
    
[[menu.main]]
    parent = "download"
    name = "MacOS"
    url = "https://github.com/openMSX/openMSX/releases/download/RELEASE_0_13_0/openmsx-0.13.0-mac-x86_64-bin.dmg"
    weight = 3

[[menu.main]]
    parent = "download"
    name = "More downloads"
    url = "/page/download/"
    weight = 4

[[menu.main]]
    name = "3rd Party"
    url = "/page/3rdparty/"
    weight = 3
    
[[menu.main]]
    identifier = "contact"
    name = "Contact"
    weight = 4

[[menu.main]]
    parent = "contact"
    name = "Contact"
    url = "/page/contact/"
    weight = 1
    
[[menu.main]]
    parent = "contact"
    name = "Forum (MRC)"
    url = "http://www.msx.org/forum/semi-msx-talk/openmsx"
    weight = 1
    
[[menu.main]]
    parent = "contact"
    name = "Project Page"
    url = "https://github.com/openMSX/"
    weight = 2
